### ISSUE TITLE
Deprecated Grakn API

### ISSUE THREAD

**Issue by cvediver** [cetfor/PaperMachete#3]
Newer versions of Grakn run into problems with the `queries/` scripts, e.g.
```
== [3] Run all CWE queries =====================================================
... <truncated> ...
Traceback (most recent call last):
... <truncated> ...
    graph = grakn.Client(uri='http://localhost:4567', keyspace=keyspace)
AttributeError: module 'grakn' has no attribute 'Client'
```
PR incoming...

**Comment by cetfor** [comment]
Awesome, thanks for submitting this issue!  I'd be happy to review your PR and help in any way to get this updated.  If you run into any bandwidth issues just let me know and I'll hop in to help out at night and over the weekend.
